file_name = "sample.txt"
file = open(file_name, "w")
file.write("Hello, this is the first line.\n")
file.write("File handling in Python is easy!\n")
file.close()   
print("Data written successfully.\n")
file = open(file_name, "r")
content = file.read()
print("File content after writing:")
print(content)
file.close()
file = open(file_name, "a")
file.write("This line is appended later.\n")
file.close()
print("\nData appended successfully.\n")
file = open(file_name, "r")
updated_content = file.read()
print("File content after appending:")
print(updated_content)
file.close()